= Run Command On Changes
:frombash: https://github.com/jzacsh/bin/blob/f38719fdc6795/share/runonchange
:locref: https://github.com/jzacsh/runonchange/blob/
:gomodules: https://blog.golang.org/migrating-to-go-modules

== Overview

Runs an arbitrary command when some filesystem even changes with given filepath(s)

.installation
----
$ go get github.com/jzacsh/runonchange
----

.usage
----
$ runonchange help
Runs COMMAND everytime filesystem events happen under a DIR_TO_WATCH.

  Usage:  COMMAND [-cdR] [-w WAIT_DURATION] [-i|-r FILE_PATTERN] [DIR_TO_WATCH, ...]

  Description:
    This program watches filesystem events under DIR_TO_WATCH. When an event
    occurs, there is an associated file that caused the event. Those are the
    files whose paths FILE_PATTERNs are compared against. Except as described by
    -r and -i, said file system events under DIR_TO_WATCH trigger COMMAND to be
    run in the current $SHELL.

  Arguments:
    DIR_TO_WATCH: indicates the directory whose ancestor file events should
    trigger COMMAND to be run. Defaults to the current working directory.
    Multiple directories can be passed.

    DIR_TO_WATCH arguments must be the last on the commandline.

  Flags:
    -d: indicates debugging output should be printed.

    -R: indicates a recursive watch should be established under DIR_TO_WATCH.
    That is: COMMAND will be triggered by more than just file events of
    immediate children to DIR_TO_WATCH.

    -c: indicates long-running COMMANDs should be killed when newer triggering
    events are received.

    -w WAIT_DURATION: indicates minimum seconds to wait after starting COMMAND,
    before re-running COMMAND for new filesystem events. Defaults to 2s.

    -i FILE_PATTERN: only run COMMAND if match is not made (invert/ignore)
    -r FILE_PATTERN: only run COMMAND if match is made

      FILE_PATTERN is a regular expression used to match against files whose
      events are as described by the two flags: -i (ignore), -r (restrict).

      If -i than events whose files match FILE_PATTERN will be ignored, thus not
      triggering COMMAND when COMMAND would normally run.

      If -r than only events whose files match FILE_PATTERN can trigger COMMAND.

      Valid FILE_PATTERN strings are those accepted by:
        https://golang.org/pkg/regexp/#Compile
----

=== gotchas

.pesky `bad interpreter: Text file busy`
So you're in terminal a, like:
`$ $EDITOR ./myscript.sh`
... and you're editing, saving, editing, saving, etc.

.and meanwhile, `runonchange` is acting funny:
----
$ runonchange ./myscript.sh # terminal b

# terminal b: meanwhile, *sometimes* you get:
   `bash: ./myscript.sh: /bin/bash: bad interpreter: Text file busy``
----
The solution is: terminal b needs to give your bash script a moment on disk
before we ask bash to start parsing the file again:
`$ runonchange 'sleep 0.1; ./myscript.sh'`
Why? I've no clue... Would love to hear from someone on this...

== development

This codebase uses {gomodules}[golang's modules system]. tl;dr is:

----
$ go buld ./... # to recompile your changes
# now a new ./runonchange exec exists

$ go test ./... # to run unit tests
$ go mod tidy   # to update dependency changes you've made
----

j/k, there's no unit tests. feel free to add some!

=== origin & copying

This is a port {frombash}[from an old bash script of mine] to Golang.

Also, see `./LICENSE` for copyright.
